title: Lokallisten Langeland
author:
  name: Søren Ramsing
  email: s.ramsing@outlook.dk
description: Lokallisten Langeland
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - _pages/2025-03-08-kontakt.md
minima:
  skin: classic
