title: Lokallisten Langeland
author:
  name: Søren Ramsing
  email: s.ramsing@outlook.dk
description: Lokallisten Langeland
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - kontakt.md
minima:
  skin: classic
collections:
  pages:
    collections_dir: _pages
    output: true
    permalink: /:path
